### ISSUE TITLE
Create main entrypoint TeleOp (Driver) OpModes (Please See Description)

### ISSUE THREAD

**Issue by WebCoder49** [Brighton-FTC/FTC-2023#25]
Team 1|Team 2
-|-
Drivetrain|Drivetrain
Team 1's lift (look at `TestTeam1Lift`)|Team 2's lift (look at `TestTeam2Lift`)

Please ensure you note down the controls and hardware used in the comment at the top.

**Comment by sbottingota** [comment]
Should I create Team1TeleOp task/file as @la-reine-c  hasn't started on that yet.

**Comment by sbottingota** [comment]
Team 1 issue: https://github.com/orgs/Brighton-FTC/projects/2/views/1?pane=issue&itemId=23935190
Team 1 code: https://github.com/Brighton-FTC/FTC-2023/blob/workspace_sbottingota/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opModes/team1/teleop/Team1TeleOp.java

Team 2 issue: https://github.com/orgs/Brighton-FTC/projects/2/views/1?pane=issue&itemId=23935190
Team 2 code: https://github.com/Brighton-FTC/FTC-2023/blob/workspace_sbottingota/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opModes/team2/Team2TeleOp.java

(Both need testing)
