### ISSUE TITLE
Look into installing CV library

### ISSUE THREAD

**Issue by WebCoder49** [Brighton-FTC/FTC-2023#27]

**Comment by sbottingota** [comment]
Instructions: https://docs.ftclib.org/ftclib/vision/computer-vision

As we are using gradle, we could use it to install `OpenCV`.

**Comment by WebCoder49** [comment]
That's a good idea; I think [EasyOpenCV](https://github.com/OpenFTC/EasyOpenCV) is a fork of OPenCV specifically designed for FTC. Does it fit your needs?

**Comment by sbottingota** [comment]
According to the [readme file](https://github.com/OpenFTC/EasyOpenCV/blob/master/readme.md) from the `EasyOpenCV` library, you can do this like:
```
dependencies {
    implementation 'org.openftc:easyopencv:1.6.2'
} 
```

**Comment by sbottingota** [comment]
There are about three `build.gradle` files in the project. Which one should I use?
