### ISSUE TITLE
use tensorflow to identify custom sleeve

### ISSUE THREAD

**Issue by 12sliu** [Brighton-FTC/FTC-2023#32]
I feel like there has to be a better way to do this that's less complicated, but whatever

**Comment by WebCoder49** [comment]
@12sliu , this diagram (Leconfield's House Robotics Conceptual Flowchart) may be a useful idea for custom sleeves using TFOD.

![image](https://user-images.githubusercontent.com/69071853/226118788-68aebacb-a894-4673-87a3-c9478072cff5.png)

**Comment by WebCoder49** [comment]
Duplicate of #26 . I assume this is why you deleted it from the project.
