### ISSUE TITLE
Lift / Arm for Team 1

### ISSUE THREAD

**Issue by WebCoder49** [Brighton-FTC/FTC-2023#4]
* To pick up game pieces

![Image](https://user-images.githubusercontent.com/69071853/213863248-33b4a797-acc6-47fb-8a1a-6bca5ca69d83.png)

**Comment by WebCoder49** [comment]
* Maybe mechanism to hold as well

**Comment by WebCoder49** [comment]
Need more information of engineering

**Comment by 12sliu** [comment]
will wait until info from engineering is delivered

**Comment by WebCoder49** [comment]
![Image](https://user-images.githubusercontent.com/69071853/216655617-cf42feda-2618-436c-b0cf-a076965c275d.jpg)

**Comment by 12sliu** [comment]
have pushed a test version to my workspace, compiles successfully, but someone please peer review my code before testing
